### ISSUE TITLE
Pick out domain name

### ISSUE THREAD

**Issue by Zggis** [Zggis/Rookies#10]
You can pick out a name here:
https://console.aws.amazon.com/route53/home?region=us-west-2#DomainRegistration:

**Comment by johnrerick** [comment]
John and Sean completed this

**Comment by Zggis** [comment]
Domain name has been created and certificate has been installed
www.rookiesmobile.com/dev
Note: The /dev will direct to the development environment, when we are ready for a production environment I will create the production environment at www.rookiesmobile.com
